name: freevc
channels:
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - asttokens=3.0.0=pyhd8ed1ab_1
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.8.3=hbd8a1cb_0
  - comm=0.2.3=pyhe01879c_0
  - debugpy=1.8.11=py311h6a678d5_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.0=pyhd8ed1ab_0
  - expat=2.7.1=h6a678d5_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - ipykernel=6.30.1=pyh82676e8_0
  - ipython=9.4.0=pyhfa0c392_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.8.1=pyh31011fe_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libsodium=1.0.18=h36c2ea0_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - ncurses=6.5=h7934f7d_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - openssl=3.0.17=h5eee18b_0
  - parso=0.8.4=pyhd8ed1ab_1
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pip=25.1=pyhc872135_2
  - prompt-toolkit=3.0.51=pyha770c72_0
  - psutil=5.9.0=py311h5eee18b_1
  - pthread-stubs=0.3=h0ce48e5_1
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - python=3.11.13=h1a3bd86_0
  - pyzmq=26.2.0=py311h6a678d5_0
  - readline=8.2=h5eee18b_0
  - setuptools=78.1.1=py311h06a4308_0
  - sqlite=3.50.2=hb25bd0a_1
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tk=8.6.14=h993c535_1
  - tornado=6.5.1=py311h5eee18b_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.14.1=pyhe01879c_0
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - wheel=0.45.1=py311h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zeromq=4.3.5=h6a678d5_0
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - absl-py==2.3.1
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.0
      - aiosignal==1.4.0
      - annotated-types==0.7.0
      - annoy==1.17.3
      - anyio==4.10.0
      - argcomplete==3.6.2
      - attrs==25.4.0
      - audioread==3.0.1
      - beautifulsoup4==4.14.2
      - cachetools==5.5.2
      - certifi==2025.8.3
      - cffi==1.17.1
      - charset-normalizer==3.4.2
      - click==8.3.0
      - contourpy==1.3.3
      - cycler==0.12.1
      - datasets==4.1.1
      - decorator==5.2.1
      - dill==0.4.0
      - distro==1.9.0
      - fastdtw==0.3.4
      - filelock==3.13.1
      - fonttools==4.59.1
      - frozenlist==1.8.0
      - fsspec==2024.6.1
      - gdown==5.2.0
      - glob2==0.7
      - google-api-core==2.25.1
      - google-auth==2.40.3
      - google-auth-oauthlib==0.4.6
      - google-cloud-texttospeech==2.29.0
      - googleapis-common-protos==1.70.0
      - grpcio==1.74.0
      - grpcio-status==1.74.0
      - h11==0.16.0
      - h5py==3.14.0
      - hf-xet==1.1.7
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.34.4
      - hyperpyyaml==1.2.2
      - idna==3.10
      - jinja2==3.1.4
      - jiter==0.10.0
      - joblib==1.5.1
      - kaldiio==2.18.1
      - kiwisolver==1.4.9
      - lazy-loader==0.4
      - librosa==0.11.0
      - llvmlite==0.44.0
      - markdown==3.8.2
      - markupsafe==3.0.2
      - matplotlib==3.10.5
      - mpmath==1.3.0
      - msgpack==1.1.1
      - multidict==6.7.0
      - multiprocess==0.70.16
      - munch==4.0.0
      - narwhals==2.5.0
      - networkx==3.3
      - numba==0.61.2
      - numpy==1.25.2
      - nvidia-cublas-cu12==12.6.4.1
      - nvidia-cuda-cupti-cu12==12.6.80
      - nvidia-cuda-nvrtc-cu12==12.6.77
      - nvidia-cuda-runtime-cu12==12.6.77
      - nvidia-cudnn-cu12==9.5.1.17
      - nvidia-cufft-cu12==11.3.0.4
      - nvidia-cufile-cu12==1.11.1.6
      - nvidia-curand-cu12==10.3.7.77
      - nvidia-cusolver-cu12==11.7.1.2
      - nvidia-cusparse-cu12==12.5.4.2
      - nvidia-cusparselt-cu12==0.6.3
      - nvidia-nccl-cu12==2.26.2
      - nvidia-nvjitlink-cu12==12.6.85
      - nvidia-nvtx-cu12==12.6.77
      - oauthlib==3.3.1
      - openai==1.107.2
      - packaging==25.0
      - pacmap==0.8.0
      - pandas==2.3.1
      - parallel-wavegan==0.6.1
      - pillow==11.0.0
      - platformdirs==4.3.8
      - plotly==6.3.0
      - pooch==1.8.2
      - propcache==0.4.0
      - proto-plus==1.26.1
      - protobuf==3.20.3
      - pyarrow==21.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pycparser==2.22
      - pydantic==2.11.8
      - pydantic-core==2.33.2
      - pydub==0.25.1
      - pyparsing==3.2.3
      - pysocks==1.7.1
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.2
      - regex==2025.7.34
      - requests==2.32.4
      - requests-oauthlib==2.0.0
      - resampy==0.4.3
      - rsa==4.9.1
      - ruamel-yaml==0.18.16
      - ruamel-yaml-clib==0.2.14
      - safetensors==0.6.2
      - scikit-learn==1.7.1
      - scipy==1.16.2
      - seaborn==0.13.2
      - sentencepiece==0.2.1
      - six==1.17.0
      - sniffio==1.3.1
      - soundfile==0.13.1
      - soupsieve==2.8
      - soxr==0.5.0.post1
      - speechbrain==1.0.3
      - sympy==1.13.3
      - tensorboard==2.7.0
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - tensorboardx==2.6.4
      - threadpoolctl==3.6.0
      - tokenizers==0.21.4
      - tomlkit==0.13.3
      - torch==2.7.1+cu126
      - torchaudio==2.7.1+cu126
      - torchvision==0.22.1+cu126
      - tqdm==4.67.1
      - transformers==4.55.2
      - triton==3.3.1
      - typing-extensions==4.12.2
      - typing-inspection==0.4.1
      - tzdata==2025.2
      - urllib3==2.5.0
      - wavenet-vocoder==0.1.1
      - webrtcvad==2.0.10
      - werkzeug==3.1.3
      - xmltodict==1.0.2
      - xxhash==3.6.0
      - yarl==1.22.0
      - yq==3.4.3
prefix: /home/vunv/miniconda3/envs/freevc
